# Generated by Django 5.0.14 on 2026-10-04 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=50, unique=True)),
                ('unit', models.CharField(choices=[('C', 'Celsius'), ('F', 'Fahrenheit')], default='C', max_length=1)),
                ('expected_interval_minutes', models.PositiveIntegerField(default=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['external_id'],
            },
        ),
        migrations.CreateModel(
            name='Refrigerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refrigerators', to='fridges.branch')),
            ],
            options={
                'ordering': ['branch__name', 'name'],
                'unique_together': {('branch', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LoggerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, help_text='Blank = currently active.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='fridges.logger')),
                ('refrigerator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logger_assignments', to='fridges.refrigerator')),
            ],
            options={
                'ordering': ['logger__external_id', 'start_at'],
            },
        ),
    ]
