# Generated by Django 5.0.14 on 2026-10-05 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fridges', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['name'], 'verbose_name_plural': 'branches'},
        ),
    ]
