# Generated by Django 5.0.14 on 2026-10-04 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fridges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('file_hash', models.CharField(max_length=64, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('valid_count', models.PositiveIntegerField(default=0)),
                ('invalid_count', models.PositiveIntegerField(default=0)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('unresolved_count', models.PositiveIntegerField(default=0)),
                ('fallback_logger', models.ForeignKey(blank=True, help_text='Used for every row only when the file has no Logger-ID column.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fallback_uploads', to='fridges.logger')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TemperatureReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_logger_code', models.CharField(blank=True, max_length=50)),
                ('raw_timestamp', models.CharField(blank=True, max_length=100)),
                ('raw_temperature', models.CharField(blank=True, max_length=50)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('temperature_c', models.FloatField(blank=True, null=True)),
                ('temperature_unit', models.CharField(blank=True, choices=[('C', 'Celsius'), ('F', 'Fahrenheit')], max_length=1)),
                ('is_valid', models.BooleanField(default=True)),
                ('reason', models.CharField(blank=True, choices=[('missing_logger_code', 'No logger code (no column, no fallback)'), ('invalid_timestamp', 'Invalid timestamp'), ('invalid_temperature', 'Invalid temperature'), ('unknown_logger', 'Unknown logger — not yet in the registry'), ('no_active_assignment', 'No logger assignment covers this time')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readings', to='fridges.logger')),
                ('refrigerator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readings', to='fridges.refrigerator')),
                ('uploaded_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='readings.uploadedfile')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddConstraint(
            model_name='temperaturereading',
            constraint=models.UniqueConstraint(condition=models.Q(('is_valid', True)), fields=('raw_logger_code', 'timestamp'), name='unique_valid_reading_per_logger_code_timestamp'),
        ),
    ]
